BertModel: /mnt/nvme_disk/user8_data/BN5212-final-VLMR/hf/bert-base-uncased
accelerator: gpu
base_dir: ./data/mimic_cxr/images
batch_size: 16
delta_file: /mnt/nvme_disk/user8_data/BN5212-final-VLMR/DiscBERT/discbert.pth
devices: 1
learning_rate: 2.0e-05
max_epochs: 15
num_workers: 8
precision: bf16-mixed
predict: true
predictroad: /mnt/nvme_disk/user8_data/BN5212-final-VLMR/DiscBERT/sn_predictions.csv
prefetch_factor: 4
savedmodel_path: /mnt/nvme_disk/user8_data/BN5212-final-VLMR/DiscBERT/hall_results
strategy: ddp
test: false
test_batch_size: 16
testroad: ./data/manual_annotaion.csv
train: false
trainroad: ./data/train.csv
val_batch_size: 16
val_check_interval: 1.0
validate: false
valroad: ./data/val.csv
